# Generated by Django 5.0.1 on 2025-07-15 10:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('travel_type', models.CharField(choices=[('business', 'Business'), ('scientific', 'Scientific'), ('vacation', 'Vacation'), ('pilgrimage', 'Pilgrimage')], max_length=20)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('residence', models.CharField(blank=True, max_length=200)),
                ('objectives', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('advice_data', models.JSONField(blank=True, null=True)),
                ('is_synced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuickDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('market', 'Market'), ('hotel', 'Hotel'), ('restaurant', 'Restaurant'), ('religious', 'Religious Place'), ('cultural', 'Cultural Site'), ('hospital', 'Hospital'), ('transport', 'Transport')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('visited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travels.travel')),
            ],
        ),
        migrations.CreateModel(
            name='TravelAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice_type', models.CharField(choices=[('do', 'Do'), ('dont', "Don't"), ('bonus', 'Bonus Tip')], max_length=20)),
                ('content', models.TextField()),
                ('priority', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travels.travel')),
            ],
            options={
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('uv_index', models.FloatField(blank=True, null=True)),
                ('description', models.CharField(max_length=100)),
                ('advice', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travels.travel')),
            ],
        ),
    ]
